
# API 配置
api:
  # 基础 URL
  base_url: "https://yuyue.library.sh.cn"
  # 楼层 ID
  floor_id: "4"
  # 图书馆 ID
  library_id: "1"
  # 座位预订类型
  seat_reservation_type: "2"
  # 时间段预订类型
  period_reservation_type: "14"
  # 预订请求间隔（毫秒）
  reservation_interval: 1000

# 区域优先级配置
area_priority:
  - "西"
  - "东"
  - "北"
  - "南"

# 日志配置
logging:
  level: "INFO"
  rotation: "1 day"
  retention: "7 days"
  encoding: "utf-8"

# 预订配置
reservation:
  # 预订提前天数
  days_ahead: 6

# 捡漏配置
snipe_interval: 300  # 捡漏频率(秒) 
